### PR TITLE
Update to Swift 3.1

### PR DESCRIPTION
**Pull request by cemolcay**
- Updated Swift 3.1 using xcode converter.
- Added Array extensions for using directly from array types.
Just call [1, 2].permutations(...) or [1, 2].combinations
- Podspec updated to version 1.1
- Added osx, tvos and watchos targets to podspec
- Added documentations.
- Added array extension tests.

### CODE REVIEW

**Comment by almata** [comment]
Hello Cem. I've added you as a collaborator on this repo so you can manage the changes yourself, as I'm a bit away from Swift these days. Hope you don't mind it. And many thanks for your time and effort.

**Comment by cemolcay** [comment]
Hi Albert, thanks. I'm gonna merge this and try to release a new version on cocoapods as well.

**Comment by cemolcay** [comment]
I can not push the new version to cocoapods because I'm not an owner of the pod.
If you add me as an owner by 
`pod trunk add-owner Combinatorics ccemolcay@gmail.com`
I could push the new version, or you could update the new pod.
Thanks!

**Comment by almata** [comment]
Sorry for the delay. I've just podtrunkaddowner'ed you a minute ago :)

**Pull request merged**
